### ISSUE TITLE
How to use drf_turbo serializer

### ISSUE THREAD

**Issue by hossamdebyene** [Mng-dev-ai/drf-turbo#9]
* drf-turbo version:0.1.5
* Python version:3.9
* Operating System:win10

### Description

I am trying to save data in the postgres using django with the serializer implemented in cython

### What I Did
I followed the process you written in the documentations but the cython build i didn't know how to build and if i use dt.serializer it gives me in save no object has no attribute 'create' and if i use dr.ModelSerializer 
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by Mng-dev-ai** [comment]
Can you show me your code please?

**Comment by hossamdebyene** [comment]
![Screenshot (20)_LI](https://user-images.githubusercontent.com/79216694/170191016-444f47e3-843a-400e-b3ed-9223ef8f5970.jpg)
![Screenshot (18)](https://user-images.githubusercontent.com/79216694/170191063-cdf80ab4-1077-4837-9ee4-e19f03ebde6b.png)

These are the serializers with the code i highlighted under it

**Comment by Mng-dev-ai** [comment]
I can't see any errors in the console, all I see is the instance of the serializer only.
Can you please share how did you use the serializer within the view and what errors you got?

**Comment by HDebiane** [comment]
Did you checked the both pictures I attached with the issue 
i used the serializer to save data in the loop the problem is when using the serializer.save() it gives the highlighted issue in the first picture in case you can send me your email or phone number to contact you

**Comment by Mng-dev-ai** [comment]
I can't see where do you use the serializer, please update your code with a clear example.

**Comment by DariaVStepanova** [comment]
Hello,
Looks like I have similar error. 
drf-turbo version:0.1.5
Python 3.6.9
Django version 3.2.15

**Description**
I call serializer from apiviews.py and the error is 
```
Traceback (most recent call last):
  File "drf_turbo/fields.pyx", line 214, in drf_turbo.fields.Field.get_attribute
  File "drf_turbo/utils.pyx", line 57, in drf_turbo.utils.get_attribute
  File "drf_turbo/utils.pyx", line 64, in drf_turbo.utils.get_attribute
AttributeError: 'xxx' object has no attribute 'xxx_atr'
```
The error appear when nested serializer called.
I cannot share my code but will do my best to answer your questions.

**Comment by Mng-dev-ai** [comment]
Hello @DarViSte, Can you share any examples that I can test?

**Comment by Mng-dev-ai** [comment]
Thank you @DarViSte 
I should have mentioned that in the docs, I renamed `to_representation` > `serialize` and `to_internal_value` > `deserialize`
so it should be:
```
def serialize(self, instance, context):
     ...
```
btw, you must add `context` argument to the method

**Comment by DarViSte** [comment]
Hello @Mng-dev-ai  
Thank you very much for your help. The error is solved now. 
Just one question. When I call regular serializer serialization runs one by one, but when I call drf-turbo it gets whole queryset at once. Is it how it work or I do something wrong.

P.S. I put the context as parameter just forgot to write it :)

**Comment by Mng-dev-ai** [comment]
Not sure what you mean by getting the whole queryset at once

**Comment by DarViSte** [comment]
@Mng-dev-ai  I'll try to explain. I have now two serializers, old one and drf-turbo, when I run query first with one and then with another I have a different result:
Serializer:
```
class XXXSerializer(serializer.Serializer):
   info = userXXXSerializer(read_only=True)
   
   def to_representation(self, instance, context):
       xxx = instance
       print (xxx)
```
it prints out:
```
Pick object (1)
Pick object (2)
Pick object (3)
...
```
When I call drf-turbo serializer, result for print(xxx) is:

`<QuerySet [<Pick: Pick object (1)>, <Pick: Pick object (2)>, <Pick: Pick object (3)>...']>`

I have a feeling that it is some small bug in my script which I do not see

**Comment by DarViSte** [comment]
Actually I solved the problem by calling serializer in a loop from apiviews.py

Thank you for your help!!!

**Comment by DarViSte** [comment]
Hello @Mng-dev-ai  Thank you very much for your help. Looks like that the question above is still on the surface :) Is it so that drf-turbo works with single objects, not sets?
Like in this example:
```
serializer = UserSerializer(user)
serializer.data
``` 
user is just one object not a set of the same objects.

**Comment by Mng-dev-ai** [comment]
Thank you @DarViSte, I confirm that there's a bug with overriding serialize method
I will try to fix it once I get some free time, PRs are welcome!

**Comment by Mng-dev-ai** [comment]
The way `drf-turbo` working is a little bit different than rest_framework so as you said when you print(xxx) the result is:
`<QuerySet [<Pick: Pick object (1)>, <Pick: Pick object (2)>, <Pick: Pick object (3)>...']>`
So for your example, you need to do something like that:
```
 def serialize(self, instance, context):
    if self.many:
        for o in instance:
            # add your logic here
```
Conclusion: If you need to override serialize method then you need to add some extra code than what you used to do in rest_framework otherwise it should work as usual like the below example:
```
class UserSerializer(dt.Serializer):
    email = dt.EmailField()
class ProfileSerializer(dt.Serializer):
    user = UserSerializer()
user1 = User(email="test1@gmail.com")
user2 = User(email="test2@gmail.com")
profile1 = Profile(user=user1)
profile2 = Profile(user=user2)
profiles = [profile1,profile2]
serializer = ProfileSerializer(profiles,many=True)
serializer.data
```
My main goal when I created this package was to be fast as possible so I had to give up some features to achieve that but I might change that in the future

**Comment by DarViSte** [comment]
@Mng-dev-ai  Thank you for your advice! I'll try the logic which you've suggested.
Actually looks like using drf-turbo does not help a lot because logic of my serializer is too complicated and all looping and nesting within serializer still  take a lot of time
